[package]
name = "job-book"
version = "0.1.0"
authors = ["ZhengYu, Xu <zen-xu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
